# https://docs.travis-ci.com/user/reference/linux/
dist: focal

before_install:
- sudo apt-get update

# https://github.com/koalaman/shellcheck/issues/589
addons:
  apt:
    packages:
    - shellcheck        # seems included: https://github.com/koalaman/shellcheck/wiki/TravisCI
    - zstd		# needed from 'build_qemu_image.sh'
    - qemu		# needed from 'build_qemu_image.sh'
    - qemu-user-static

# see http://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - bb@npl.de

sudo: required

# if one fails, the build is marked b0rken
script:
  - 'SC=SC2086 && shellcheck --shell=dash --exclude=$SC run-amd64.sh'
  - 'AUTO=true ./run-amd64.sh'
  - './build_qemu_image.sh'
